/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.salesforce.storagecloud;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BKProxyLogRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3059995069984128881L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BKProxyLogRecord\",\"namespace\":\"com.salesforce.storagecloud\",\"fields\":[{\"name\":\"log_start_year\",\"type\":\"int\"},{\"name\":\"log_start_month\",\"type\":\"int\"},{\"name\":\"log_start_day\",\"type\":\"int\"},{\"name\":\"log_start_hour\",\"type\":\"int\"},{\"name\":\"log_start_min\",\"type\":\"int\"},{\"name\":\"log_start_sec\",\"type\":\"int\"},{\"name\":\"log_hostname\",\"type\":\"string\"},{\"name\":\"log_filename\",\"type\":\"string\"},{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"thread\",\"type\":\"string\"},{\"name\":\"src_file\",\"type\":\"string\"},{\"name\":\"src_linenum\",\"type\":\"int\"},{\"name\":\"corr_id\",\"type\":\"string\"},{\"name\":\"extentid\",\"type\":\"string\"},{\"name\":\"extentid_long\",\"type\":\"long\"},{\"name\":\"fragmentid\",\"type\":\"long\"},{\"name\":\"content\",\"type\":[\"null\",\"string\"]},{\"name\":\"freeform_string\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private int log_start_year;
   private int log_start_month;
   private int log_start_day;
   private int log_start_hour;
   private int log_start_min;
   private int log_start_sec;
   private java.lang.CharSequence log_hostname;
   private java.lang.CharSequence log_filename;
   private long time;
   private java.lang.CharSequence type;
   private java.lang.CharSequence thread;
   private java.lang.CharSequence src_file;
   private int src_linenum;
   private java.lang.CharSequence corr_id;
   private java.lang.CharSequence extentid;
   private long extentid_long;
   private long fragmentid;
   private java.lang.CharSequence content;
   private java.lang.CharSequence freeform_string;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BKProxyLogRecord() {}

  /**
   * All-args constructor.
   * @param log_start_year The new value for log_start_year
   * @param log_start_month The new value for log_start_month
   * @param log_start_day The new value for log_start_day
   * @param log_start_hour The new value for log_start_hour
   * @param log_start_min The new value for log_start_min
   * @param log_start_sec The new value for log_start_sec
   * @param log_hostname The new value for log_hostname
   * @param log_filename The new value for log_filename
   * @param time The new value for time
   * @param type The new value for type
   * @param thread The new value for thread
   * @param src_file The new value for src_file
   * @param src_linenum The new value for src_linenum
   * @param corr_id The new value for corr_id
   * @param extentid The new value for extentid
   * @param extentid_long The new value for extentid_long
   * @param fragmentid The new value for fragmentid
   * @param content The new value for content
   * @param freeform_string The new value for freeform_string
   */
  public BKProxyLogRecord(java.lang.Integer log_start_year, java.lang.Integer log_start_month, java.lang.Integer log_start_day, java.lang.Integer log_start_hour, java.lang.Integer log_start_min, java.lang.Integer log_start_sec, java.lang.CharSequence log_hostname, java.lang.CharSequence log_filename, java.lang.Long time, java.lang.CharSequence type, java.lang.CharSequence thread, java.lang.CharSequence src_file, java.lang.Integer src_linenum, java.lang.CharSequence corr_id, java.lang.CharSequence extentid, java.lang.Long extentid_long, java.lang.Long fragmentid, java.lang.CharSequence content, java.lang.CharSequence freeform_string) {
    this.log_start_year = log_start_year;
    this.log_start_month = log_start_month;
    this.log_start_day = log_start_day;
    this.log_start_hour = log_start_hour;
    this.log_start_min = log_start_min;
    this.log_start_sec = log_start_sec;
    this.log_hostname = log_hostname;
    this.log_filename = log_filename;
    this.time = time;
    this.type = type;
    this.thread = thread;
    this.src_file = src_file;
    this.src_linenum = src_linenum;
    this.corr_id = corr_id;
    this.extentid = extentid;
    this.extentid_long = extentid_long;
    this.fragmentid = fragmentid;
    this.content = content;
    this.freeform_string = freeform_string;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return log_start_year;
    case 1: return log_start_month;
    case 2: return log_start_day;
    case 3: return log_start_hour;
    case 4: return log_start_min;
    case 5: return log_start_sec;
    case 6: return log_hostname;
    case 7: return log_filename;
    case 8: return time;
    case 9: return type;
    case 10: return thread;
    case 11: return src_file;
    case 12: return src_linenum;
    case 13: return corr_id;
    case 14: return extentid;
    case 15: return extentid_long;
    case 16: return fragmentid;
    case 17: return content;
    case 18: return freeform_string;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: log_start_year = (java.lang.Integer)value$; break;
    case 1: log_start_month = (java.lang.Integer)value$; break;
    case 2: log_start_day = (java.lang.Integer)value$; break;
    case 3: log_start_hour = (java.lang.Integer)value$; break;
    case 4: log_start_min = (java.lang.Integer)value$; break;
    case 5: log_start_sec = (java.lang.Integer)value$; break;
    case 6: log_hostname = (java.lang.CharSequence)value$; break;
    case 7: log_filename = (java.lang.CharSequence)value$; break;
    case 8: time = (java.lang.Long)value$; break;
    case 9: type = (java.lang.CharSequence)value$; break;
    case 10: thread = (java.lang.CharSequence)value$; break;
    case 11: src_file = (java.lang.CharSequence)value$; break;
    case 12: src_linenum = (java.lang.Integer)value$; break;
    case 13: corr_id = (java.lang.CharSequence)value$; break;
    case 14: extentid = (java.lang.CharSequence)value$; break;
    case 15: extentid_long = (java.lang.Long)value$; break;
    case 16: fragmentid = (java.lang.Long)value$; break;
    case 17: content = (java.lang.CharSequence)value$; break;
    case 18: freeform_string = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'log_start_year' field.
   * @return The value of the 'log_start_year' field.
   */
  public java.lang.Integer getLogStartYear() {
    return log_start_year;
  }

  /**
   * Sets the value of the 'log_start_year' field.
   * @param value the value to set.
   */
  public void setLogStartYear(java.lang.Integer value) {
    this.log_start_year = value;
  }

  /**
   * Gets the value of the 'log_start_month' field.
   * @return The value of the 'log_start_month' field.
   */
  public java.lang.Integer getLogStartMonth() {
    return log_start_month;
  }

  /**
   * Sets the value of the 'log_start_month' field.
   * @param value the value to set.
   */
  public void setLogStartMonth(java.lang.Integer value) {
    this.log_start_month = value;
  }

  /**
   * Gets the value of the 'log_start_day' field.
   * @return The value of the 'log_start_day' field.
   */
  public java.lang.Integer getLogStartDay() {
    return log_start_day;
  }

  /**
   * Sets the value of the 'log_start_day' field.
   * @param value the value to set.
   */
  public void setLogStartDay(java.lang.Integer value) {
    this.log_start_day = value;
  }

  /**
   * Gets the value of the 'log_start_hour' field.
   * @return The value of the 'log_start_hour' field.
   */
  public java.lang.Integer getLogStartHour() {
    return log_start_hour;
  }

  /**
   * Sets the value of the 'log_start_hour' field.
   * @param value the value to set.
   */
  public void setLogStartHour(java.lang.Integer value) {
    this.log_start_hour = value;
  }

  /**
   * Gets the value of the 'log_start_min' field.
   * @return The value of the 'log_start_min' field.
   */
  public java.lang.Integer getLogStartMin() {
    return log_start_min;
  }

  /**
   * Sets the value of the 'log_start_min' field.
   * @param value the value to set.
   */
  public void setLogStartMin(java.lang.Integer value) {
    this.log_start_min = value;
  }

  /**
   * Gets the value of the 'log_start_sec' field.
   * @return The value of the 'log_start_sec' field.
   */
  public java.lang.Integer getLogStartSec() {
    return log_start_sec;
  }

  /**
   * Sets the value of the 'log_start_sec' field.
   * @param value the value to set.
   */
  public void setLogStartSec(java.lang.Integer value) {
    this.log_start_sec = value;
  }

  /**
   * Gets the value of the 'log_hostname' field.
   * @return The value of the 'log_hostname' field.
   */
  public java.lang.CharSequence getLogHostname() {
    return log_hostname;
  }

  /**
   * Sets the value of the 'log_hostname' field.
   * @param value the value to set.
   */
  public void setLogHostname(java.lang.CharSequence value) {
    this.log_hostname = value;
  }

  /**
   * Gets the value of the 'log_filename' field.
   * @return The value of the 'log_filename' field.
   */
  public java.lang.CharSequence getLogFilename() {
    return log_filename;
  }

  /**
   * Sets the value of the 'log_filename' field.
   * @param value the value to set.
   */
  public void setLogFilename(java.lang.CharSequence value) {
    this.log_filename = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.lang.Long value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'thread' field.
   * @return The value of the 'thread' field.
   */
  public java.lang.CharSequence getThread() {
    return thread;
  }

  /**
   * Sets the value of the 'thread' field.
   * @param value the value to set.
   */
  public void setThread(java.lang.CharSequence value) {
    this.thread = value;
  }

  /**
   * Gets the value of the 'src_file' field.
   * @return The value of the 'src_file' field.
   */
  public java.lang.CharSequence getSrcFile() {
    return src_file;
  }

  /**
   * Sets the value of the 'src_file' field.
   * @param value the value to set.
   */
  public void setSrcFile(java.lang.CharSequence value) {
    this.src_file = value;
  }

  /**
   * Gets the value of the 'src_linenum' field.
   * @return The value of the 'src_linenum' field.
   */
  public java.lang.Integer getSrcLinenum() {
    return src_linenum;
  }

  /**
   * Sets the value of the 'src_linenum' field.
   * @param value the value to set.
   */
  public void setSrcLinenum(java.lang.Integer value) {
    this.src_linenum = value;
  }

  /**
   * Gets the value of the 'corr_id' field.
   * @return The value of the 'corr_id' field.
   */
  public java.lang.CharSequence getCorrId() {
    return corr_id;
  }

  /**
   * Sets the value of the 'corr_id' field.
   * @param value the value to set.
   */
  public void setCorrId(java.lang.CharSequence value) {
    this.corr_id = value;
  }

  /**
   * Gets the value of the 'extentid' field.
   * @return The value of the 'extentid' field.
   */
  public java.lang.CharSequence getExtentid() {
    return extentid;
  }

  /**
   * Sets the value of the 'extentid' field.
   * @param value the value to set.
   */
  public void setExtentid(java.lang.CharSequence value) {
    this.extentid = value;
  }

  /**
   * Gets the value of the 'extentid_long' field.
   * @return The value of the 'extentid_long' field.
   */
  public java.lang.Long getExtentidLong() {
    return extentid_long;
  }

  /**
   * Sets the value of the 'extentid_long' field.
   * @param value the value to set.
   */
  public void setExtentidLong(java.lang.Long value) {
    this.extentid_long = value;
  }

  /**
   * Gets the value of the 'fragmentid' field.
   * @return The value of the 'fragmentid' field.
   */
  public java.lang.Long getFragmentid() {
    return fragmentid;
  }

  /**
   * Sets the value of the 'fragmentid' field.
   * @param value the value to set.
   */
  public void setFragmentid(java.lang.Long value) {
    this.fragmentid = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.CharSequence getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'freeform_string' field.
   * @return The value of the 'freeform_string' field.
   */
  public java.lang.CharSequence getFreeformString() {
    return freeform_string;
  }

  /**
   * Sets the value of the 'freeform_string' field.
   * @param value the value to set.
   */
  public void setFreeformString(java.lang.CharSequence value) {
    this.freeform_string = value;
  }

  /**
   * Creates a new BKProxyLogRecord RecordBuilder.
   * @return A new BKProxyLogRecord RecordBuilder
   */
  public static com.salesforce.storagecloud.BKProxyLogRecord.Builder newBuilder() {
    return new com.salesforce.storagecloud.BKProxyLogRecord.Builder();
  }

  /**
   * Creates a new BKProxyLogRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BKProxyLogRecord RecordBuilder
   */
  public static com.salesforce.storagecloud.BKProxyLogRecord.Builder newBuilder(com.salesforce.storagecloud.BKProxyLogRecord.Builder other) {
    return new com.salesforce.storagecloud.BKProxyLogRecord.Builder(other);
  }

  /**
   * Creates a new BKProxyLogRecord RecordBuilder by copying an existing BKProxyLogRecord instance.
   * @param other The existing instance to copy.
   * @return A new BKProxyLogRecord RecordBuilder
   */
  public static com.salesforce.storagecloud.BKProxyLogRecord.Builder newBuilder(com.salesforce.storagecloud.BKProxyLogRecord other) {
    return new com.salesforce.storagecloud.BKProxyLogRecord.Builder(other);
  }

  /**
   * RecordBuilder for BKProxyLogRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BKProxyLogRecord>
    implements org.apache.avro.data.RecordBuilder<BKProxyLogRecord> {

    private int log_start_year;
    private int log_start_month;
    private int log_start_day;
    private int log_start_hour;
    private int log_start_min;
    private int log_start_sec;
    private java.lang.CharSequence log_hostname;
    private java.lang.CharSequence log_filename;
    private long time;
    private java.lang.CharSequence type;
    private java.lang.CharSequence thread;
    private java.lang.CharSequence src_file;
    private int src_linenum;
    private java.lang.CharSequence corr_id;
    private java.lang.CharSequence extentid;
    private long extentid_long;
    private long fragmentid;
    private java.lang.CharSequence content;
    private java.lang.CharSequence freeform_string;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.salesforce.storagecloud.BKProxyLogRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.log_start_year)) {
        this.log_start_year = data().deepCopy(fields()[0].schema(), other.log_start_year);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.log_start_month)) {
        this.log_start_month = data().deepCopy(fields()[1].schema(), other.log_start_month);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.log_start_day)) {
        this.log_start_day = data().deepCopy(fields()[2].schema(), other.log_start_day);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.log_start_hour)) {
        this.log_start_hour = data().deepCopy(fields()[3].schema(), other.log_start_hour);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.log_start_min)) {
        this.log_start_min = data().deepCopy(fields()[4].schema(), other.log_start_min);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.log_start_sec)) {
        this.log_start_sec = data().deepCopy(fields()[5].schema(), other.log_start_sec);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.log_hostname)) {
        this.log_hostname = data().deepCopy(fields()[6].schema(), other.log_hostname);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.log_filename)) {
        this.log_filename = data().deepCopy(fields()[7].schema(), other.log_filename);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.time)) {
        this.time = data().deepCopy(fields()[8].schema(), other.time);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.type)) {
        this.type = data().deepCopy(fields()[9].schema(), other.type);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.thread)) {
        this.thread = data().deepCopy(fields()[10].schema(), other.thread);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.src_file)) {
        this.src_file = data().deepCopy(fields()[11].schema(), other.src_file);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.src_linenum)) {
        this.src_linenum = data().deepCopy(fields()[12].schema(), other.src_linenum);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.corr_id)) {
        this.corr_id = data().deepCopy(fields()[13].schema(), other.corr_id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.extentid)) {
        this.extentid = data().deepCopy(fields()[14].schema(), other.extentid);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.extentid_long)) {
        this.extentid_long = data().deepCopy(fields()[15].schema(), other.extentid_long);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.fragmentid)) {
        this.fragmentid = data().deepCopy(fields()[16].schema(), other.fragmentid);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.content)) {
        this.content = data().deepCopy(fields()[17].schema(), other.content);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.freeform_string)) {
        this.freeform_string = data().deepCopy(fields()[18].schema(), other.freeform_string);
        fieldSetFlags()[18] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BKProxyLogRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.salesforce.storagecloud.BKProxyLogRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.log_start_year)) {
        this.log_start_year = data().deepCopy(fields()[0].schema(), other.log_start_year);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.log_start_month)) {
        this.log_start_month = data().deepCopy(fields()[1].schema(), other.log_start_month);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.log_start_day)) {
        this.log_start_day = data().deepCopy(fields()[2].schema(), other.log_start_day);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.log_start_hour)) {
        this.log_start_hour = data().deepCopy(fields()[3].schema(), other.log_start_hour);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.log_start_min)) {
        this.log_start_min = data().deepCopy(fields()[4].schema(), other.log_start_min);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.log_start_sec)) {
        this.log_start_sec = data().deepCopy(fields()[5].schema(), other.log_start_sec);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.log_hostname)) {
        this.log_hostname = data().deepCopy(fields()[6].schema(), other.log_hostname);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.log_filename)) {
        this.log_filename = data().deepCopy(fields()[7].schema(), other.log_filename);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.time)) {
        this.time = data().deepCopy(fields()[8].schema(), other.time);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.type)) {
        this.type = data().deepCopy(fields()[9].schema(), other.type);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.thread)) {
        this.thread = data().deepCopy(fields()[10].schema(), other.thread);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.src_file)) {
        this.src_file = data().deepCopy(fields()[11].schema(), other.src_file);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.src_linenum)) {
        this.src_linenum = data().deepCopy(fields()[12].schema(), other.src_linenum);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.corr_id)) {
        this.corr_id = data().deepCopy(fields()[13].schema(), other.corr_id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.extentid)) {
        this.extentid = data().deepCopy(fields()[14].schema(), other.extentid);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.extentid_long)) {
        this.extentid_long = data().deepCopy(fields()[15].schema(), other.extentid_long);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.fragmentid)) {
        this.fragmentid = data().deepCopy(fields()[16].schema(), other.fragmentid);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.content)) {
        this.content = data().deepCopy(fields()[17].schema(), other.content);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.freeform_string)) {
        this.freeform_string = data().deepCopy(fields()[18].schema(), other.freeform_string);
        fieldSetFlags()[18] = true;
      }
    }

    /**
      * Gets the value of the 'log_start_year' field.
      * @return The value.
      */
    public java.lang.Integer getLogStartYear() {
      return log_start_year;
    }

    /**
      * Sets the value of the 'log_start_year' field.
      * @param value The value of 'log_start_year'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setLogStartYear(int value) {
      validate(fields()[0], value);
      this.log_start_year = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'log_start_year' field has been set.
      * @return True if the 'log_start_year' field has been set, false otherwise.
      */
    public boolean hasLogStartYear() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'log_start_year' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearLogStartYear() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'log_start_month' field.
      * @return The value.
      */
    public java.lang.Integer getLogStartMonth() {
      return log_start_month;
    }

    /**
      * Sets the value of the 'log_start_month' field.
      * @param value The value of 'log_start_month'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setLogStartMonth(int value) {
      validate(fields()[1], value);
      this.log_start_month = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'log_start_month' field has been set.
      * @return True if the 'log_start_month' field has been set, false otherwise.
      */
    public boolean hasLogStartMonth() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'log_start_month' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearLogStartMonth() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'log_start_day' field.
      * @return The value.
      */
    public java.lang.Integer getLogStartDay() {
      return log_start_day;
    }

    /**
      * Sets the value of the 'log_start_day' field.
      * @param value The value of 'log_start_day'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setLogStartDay(int value) {
      validate(fields()[2], value);
      this.log_start_day = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'log_start_day' field has been set.
      * @return True if the 'log_start_day' field has been set, false otherwise.
      */
    public boolean hasLogStartDay() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'log_start_day' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearLogStartDay() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'log_start_hour' field.
      * @return The value.
      */
    public java.lang.Integer getLogStartHour() {
      return log_start_hour;
    }

    /**
      * Sets the value of the 'log_start_hour' field.
      * @param value The value of 'log_start_hour'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setLogStartHour(int value) {
      validate(fields()[3], value);
      this.log_start_hour = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'log_start_hour' field has been set.
      * @return True if the 'log_start_hour' field has been set, false otherwise.
      */
    public boolean hasLogStartHour() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'log_start_hour' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearLogStartHour() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'log_start_min' field.
      * @return The value.
      */
    public java.lang.Integer getLogStartMin() {
      return log_start_min;
    }

    /**
      * Sets the value of the 'log_start_min' field.
      * @param value The value of 'log_start_min'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setLogStartMin(int value) {
      validate(fields()[4], value);
      this.log_start_min = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'log_start_min' field has been set.
      * @return True if the 'log_start_min' field has been set, false otherwise.
      */
    public boolean hasLogStartMin() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'log_start_min' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearLogStartMin() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'log_start_sec' field.
      * @return The value.
      */
    public java.lang.Integer getLogStartSec() {
      return log_start_sec;
    }

    /**
      * Sets the value of the 'log_start_sec' field.
      * @param value The value of 'log_start_sec'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setLogStartSec(int value) {
      validate(fields()[5], value);
      this.log_start_sec = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'log_start_sec' field has been set.
      * @return True if the 'log_start_sec' field has been set, false otherwise.
      */
    public boolean hasLogStartSec() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'log_start_sec' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearLogStartSec() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'log_hostname' field.
      * @return The value.
      */
    public java.lang.CharSequence getLogHostname() {
      return log_hostname;
    }

    /**
      * Sets the value of the 'log_hostname' field.
      * @param value The value of 'log_hostname'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setLogHostname(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.log_hostname = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'log_hostname' field has been set.
      * @return True if the 'log_hostname' field has been set, false otherwise.
      */
    public boolean hasLogHostname() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'log_hostname' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearLogHostname() {
      log_hostname = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'log_filename' field.
      * @return The value.
      */
    public java.lang.CharSequence getLogFilename() {
      return log_filename;
    }

    /**
      * Sets the value of the 'log_filename' field.
      * @param value The value of 'log_filename'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setLogFilename(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.log_filename = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'log_filename' field has been set.
      * @return True if the 'log_filename' field has been set, false otherwise.
      */
    public boolean hasLogFilename() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'log_filename' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearLogFilename() {
      log_filename = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public java.lang.Long getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setTime(long value) {
      validate(fields()[8], value);
      this.time = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearTime() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setType(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.type = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearType() {
      type = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'thread' field.
      * @return The value.
      */
    public java.lang.CharSequence getThread() {
      return thread;
    }

    /**
      * Sets the value of the 'thread' field.
      * @param value The value of 'thread'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setThread(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.thread = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'thread' field has been set.
      * @return True if the 'thread' field has been set, false otherwise.
      */
    public boolean hasThread() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'thread' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearThread() {
      thread = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'src_file' field.
      * @return The value.
      */
    public java.lang.CharSequence getSrcFile() {
      return src_file;
    }

    /**
      * Sets the value of the 'src_file' field.
      * @param value The value of 'src_file'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setSrcFile(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.src_file = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'src_file' field has been set.
      * @return True if the 'src_file' field has been set, false otherwise.
      */
    public boolean hasSrcFile() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'src_file' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearSrcFile() {
      src_file = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'src_linenum' field.
      * @return The value.
      */
    public java.lang.Integer getSrcLinenum() {
      return src_linenum;
    }

    /**
      * Sets the value of the 'src_linenum' field.
      * @param value The value of 'src_linenum'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setSrcLinenum(int value) {
      validate(fields()[12], value);
      this.src_linenum = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'src_linenum' field has been set.
      * @return True if the 'src_linenum' field has been set, false otherwise.
      */
    public boolean hasSrcLinenum() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'src_linenum' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearSrcLinenum() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'corr_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCorrId() {
      return corr_id;
    }

    /**
      * Sets the value of the 'corr_id' field.
      * @param value The value of 'corr_id'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setCorrId(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.corr_id = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'corr_id' field has been set.
      * @return True if the 'corr_id' field has been set, false otherwise.
      */
    public boolean hasCorrId() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'corr_id' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearCorrId() {
      corr_id = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'extentid' field.
      * @return The value.
      */
    public java.lang.CharSequence getExtentid() {
      return extentid;
    }

    /**
      * Sets the value of the 'extentid' field.
      * @param value The value of 'extentid'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setExtentid(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.extentid = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'extentid' field has been set.
      * @return True if the 'extentid' field has been set, false otherwise.
      */
    public boolean hasExtentid() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'extentid' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearExtentid() {
      extentid = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'extentid_long' field.
      * @return The value.
      */
    public java.lang.Long getExtentidLong() {
      return extentid_long;
    }

    /**
      * Sets the value of the 'extentid_long' field.
      * @param value The value of 'extentid_long'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setExtentidLong(long value) {
      validate(fields()[15], value);
      this.extentid_long = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'extentid_long' field has been set.
      * @return True if the 'extentid_long' field has been set, false otherwise.
      */
    public boolean hasExtentidLong() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'extentid_long' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearExtentidLong() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'fragmentid' field.
      * @return The value.
      */
    public java.lang.Long getFragmentid() {
      return fragmentid;
    }

    /**
      * Sets the value of the 'fragmentid' field.
      * @param value The value of 'fragmentid'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setFragmentid(long value) {
      validate(fields()[16], value);
      this.fragmentid = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'fragmentid' field has been set.
      * @return True if the 'fragmentid' field has been set, false otherwise.
      */
    public boolean hasFragmentid() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'fragmentid' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearFragmentid() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }

    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.content = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearContent() {
      content = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'freeform_string' field.
      * @return The value.
      */
    public java.lang.CharSequence getFreeformString() {
      return freeform_string;
    }

    /**
      * Sets the value of the 'freeform_string' field.
      * @param value The value of 'freeform_string'.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder setFreeformString(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.freeform_string = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'freeform_string' field has been set.
      * @return True if the 'freeform_string' field has been set, false otherwise.
      */
    public boolean hasFreeformString() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'freeform_string' field.
      * @return This builder.
      */
    public com.salesforce.storagecloud.BKProxyLogRecord.Builder clearFreeformString() {
      freeform_string = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    @Override
    public BKProxyLogRecord build() {
      try {
        BKProxyLogRecord record = new BKProxyLogRecord();
        record.log_start_year = fieldSetFlags()[0] ? this.log_start_year : (java.lang.Integer) defaultValue(fields()[0]);
        record.log_start_month = fieldSetFlags()[1] ? this.log_start_month : (java.lang.Integer) defaultValue(fields()[1]);
        record.log_start_day = fieldSetFlags()[2] ? this.log_start_day : (java.lang.Integer) defaultValue(fields()[2]);
        record.log_start_hour = fieldSetFlags()[3] ? this.log_start_hour : (java.lang.Integer) defaultValue(fields()[3]);
        record.log_start_min = fieldSetFlags()[4] ? this.log_start_min : (java.lang.Integer) defaultValue(fields()[4]);
        record.log_start_sec = fieldSetFlags()[5] ? this.log_start_sec : (java.lang.Integer) defaultValue(fields()[5]);
        record.log_hostname = fieldSetFlags()[6] ? this.log_hostname : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.log_filename = fieldSetFlags()[7] ? this.log_filename : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.time = fieldSetFlags()[8] ? this.time : (java.lang.Long) defaultValue(fields()[8]);
        record.type = fieldSetFlags()[9] ? this.type : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.thread = fieldSetFlags()[10] ? this.thread : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.src_file = fieldSetFlags()[11] ? this.src_file : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.src_linenum = fieldSetFlags()[12] ? this.src_linenum : (java.lang.Integer) defaultValue(fields()[12]);
        record.corr_id = fieldSetFlags()[13] ? this.corr_id : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.extentid = fieldSetFlags()[14] ? this.extentid : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.extentid_long = fieldSetFlags()[15] ? this.extentid_long : (java.lang.Long) defaultValue(fields()[15]);
        record.fragmentid = fieldSetFlags()[16] ? this.fragmentid : (java.lang.Long) defaultValue(fields()[16]);
        record.content = fieldSetFlags()[17] ? this.content : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.freeform_string = fieldSetFlags()[18] ? this.freeform_string : (java.lang.CharSequence) defaultValue(fields()[18]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @SuppressWarnings("unchecked")
  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @SuppressWarnings("unchecked")
  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
